export const LOADING = 'LOADING'
export const SET_ROMAN_NB = 'SET_ROMAN_NB'
export const SAGA_SUBMIT_ARAB_TO_GET_ROMAN = 'SAGA_SUBMIT_ARAB_TO_GET_ROMAN'
export const SAGA_EVENT_GET_ROMAN = 'SAGA_EVENT_GET_ROMAN'
